name: MoreExp
main: me.dkaffeine.moreexp.MoreExpMain
version: 3.5r

commands:
    moreexp:
        description: General command for this plugin
        usage: /moreexp <command>
    mex:
        description: General command for this plugin
        usage: /mex <command>        
